#!/bin/sh
set -e

# Hook for building live images
#
# This script is run in the built chroot after all packages are installed,
# before it is packed into a squashfs. This is where you can apply extra tweaks
# to the live system.

# purge fonts to reduce the size of a squashfs
#apt-get -y purge 'fonts-kacst' 'fonts-kacst-one' 'fonts-khmeros-core' 'fonts-lao' 'fonts-nanum' \
#                 'fonts-tlwg-*' 'fonts-thai-tlwg' 'ttf-indic-fonts-core' 'ttf-punjabi-fonts' \
#                 'ttf-wqy-microhei'

fontconfig-voodoo -s ja_JP
wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/sources.list.d/precise.list -O /etc/apt/sources.list.d/ubuntu-ja.list
apt-get update
apt-get upgrade --yes
apt-get clean
