#!/bin/bash -x
if [ "x$BASH" = "x" ]; then
	echo "this process is using sh, so now restarting with bash"
	logger -t "mkcdimage" "restarting with bash"
	exec bash $0 "$@"
fi
set -e

# Hook for building live images
#
# This script is run in the built chroot after all packages are installed,
# before it is packed into a squashfs. This is where you can apply extra tweaks
# to the live system.

# purge fonts to reduce the size of a squashfs
#apt-get -y purge 'fonts-kacst' 'fonts-kacst-one' 'fonts-khmeros-core' 'fonts-lao' 'fonts-nanum' \
#                 'fonts-tlwg-*' 'fonts-thai-tlwg' 'ttf-indic-fonts-core' 'ttf-punjabi-fonts' \
#                 'ttf-wqy-microhei'

#fontconfig-voodoo -s ja_JP
wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/sources.list.d/precise.list -O /etc/apt/sources.list.d/ubuntu-ja.list
# apt-get purge --yes libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-emailmerge libreoffice-gnome libreoffice-gtk libreoffice-help-en-us libreoffice-help-ja libreoffice-impress libreoffice-l10n-ja libreoffice-math libreoffice-style-human libreoffice-style-tango libreoffice-writer software-center firefox-locale-en
apt-get update
apt-get install -y linux-image-generic-lts-trusty libgl1-mesa-glx-lts-trusty xserver-xorg-lts-trusty
set +e
for i in precise quantal raring saucy; do
 apt-get purge linux-image-generic-lts-$i --auto-remove -y
done
set -e
apt-get upgrade --yes
apt-get autoremove --yes
apt-get clean

#exit 0

# --- 以下を実行させたければ上のexit 0 を外してください
echo 'LANG="ja_JP.UTF-8"' > /etc/default/locale
cat > /etc/default/keyboard <<EOM
# Check /usr/share/doc/keyboard-configuration/README.Debian for
# documentation on what to do after having modified this file.

# The following variables describe your keyboard and can have the same
# values as the XkbModel, XkbLayout, XkbVariant and XkbOptions options
# in /etc/X11/xorg.conf.

XKBMODEL="pc105"
XKBLAYOUT="jp"
XKBVARIANT=""
XKBOPTIONS=""

# If you don't want to use the XKB layout on the console, you can
# specify an alternative keymap.  Make sure it will be accessible
# before /usr is mounted.
# KMAP=/etc/console-setup/defkeymap.kmap.gz
EOM

cat > /etc/default/rcS <<EOM
#
# /etc/default/rcS
#
# Default settings for the scripts in /etc/rcS.d/
#
# For information about these variables see the rcS(5) manual page.
#
# This file belongs to the "initscripts" package.

# delete files in /tmp during boot older than x days.
# '0' means always, -1 or 'infinite' disables the feature
TMPTIME=0

# spawn sulogin during boot, continue normal boot if not used in 30 seconds
SULOGIN=no

# do not allow users to log in until the boot has completed
DELAYLOGIN=no

# assume that the BIOS clock is set to UTC time (recommended)
UTC=no

# be more verbose during the boot process
VERBOSE=no

# automatically repair filesystems with inconsistencies during boot
FSCKFIX=no
EOM

echo "Asia/Tokyo" > /etc/timezone
echo "tzdata	tzdata/Areas	select	Asia" | debconf-set-selections
echo "tzdata	tzdata/Zones/Asia	select	Tokyo" | debconf-set-selections
dpkg-reconfigure -p critical tzdata
cmp /etc/localtime  /usr/share/zoneinfo/Asia/Tokyo 
[ ! $? = 0 ] && cp -f /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# chrome
CARCH=""
if [ -d /lib64 ]; then # amd64(x86_64)
	CARCH="amd64"
else                   # i386(x86)
	CARCH="i386"
fi
wget "https://dl.google.com/linux/direct/google-chrome-stable_current_$CARCH.deb" -O /tmp/chrome.deb
dpkg -i /tmp/chrome.deb

apt-get install linux-image-genecic-lts-trusty \
                libgl1-mesa-glx-lts-trusty

#wget -O- https://www.opscode.com/chef/install.sh | bash
apt-get purge --autoremove ruby1.8
apt-get install ruby1.9.3
gem1.9.3 install chef --no-{ri,rdoc}

sudo -u 'ubuntu' -H dbus-launch gsettings set org.gnome.desktop.screensaver lock-enabled false
sudo -u 'ubuntu' -H dbus-launch gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
